"""empty message

Revision ID: 099eb03fe904
Revises: 
Create Date: 2025-01-29 17:20:07.495092

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '099eb03fe904'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audio_entities',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('uuid', sa.VARCHAR(length=128), nullable=False),
    sa.Column('filename', sa.VARCHAR(length=128), nullable=False),
    sa.Column('url', sa.VARCHAR(length=2048), nullable=False),
    sa.Column('audio_length', sa.NUMERIC(precision=5, scale=2), nullable=False),
    sa.Column('context_tag', sa.VARCHAR(length=16), nullable=True),
    sa.Column('context_text', sa.VARCHAR(length=128), nullable=True),
    sa.Column('in_disk', sa.BOOLEAN(), nullable=True),
    sa.Column('in_hitlist', sa.BOOLEAN(), nullable=False),
    sa.Column('time_added', sa.DATETIME(), nullable=False),
    sa.Column('time_removed', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id', name='pk_audio_entities'),
    sa.UniqueConstraint('uuid', name='uqx_audio_entities_uuid')
    )
    with op.batch_alter_table('audio_entities', schema=None) as batch_op:
        batch_op.create_index('idx_audio_entities_uuid', ['uuid'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audio_entities', schema=None) as batch_op:
        batch_op.drop_index('idx_audio_entities_uuid')

    op.drop_table('audio_entities')
    # ### end Alembic commands ###
