"""empty message

Revision ID: 0e223ae7b1e0
Revises: 
Create Date: 2025-01-29 15:54:17.593117

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e223ae7b1e0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('video_requests',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('filename', sa.VARCHAR(length=128), nullable=False),
    sa.Column('video_url', sa.VARCHAR(length=2048), nullable=False),
    sa.Column('video_length', sa.NUMERIC(precision=5, scale=2), nullable=False),
    sa.Column('context_tag', sa.VARCHAR(length=16), nullable=True),
    sa.Column('context_text', sa.VARCHAR(length=128), nullable=True),
    sa.Column('in_disk', sa.BOOLEAN(), nullable=True),
    sa.Column('time_added', sa.DATETIME(), nullable=False),
    sa.Column('time_removed', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id', name='pk_video_requests')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('video_requests')
    # ### end Alembic commands ###
