"""empty message

Revision ID: f3e2902dc043
Revises: 0e223ae7b1e0
Create Date: 2025-01-29 15:57:28.345978

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3e2902dc043'
down_revision = '0e223ae7b1e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('video_requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('uuid', sa.VARCHAR(length=128), nullable=False))
        batch_op.create_index('idx_video_requests_uuid', ['uuid'], unique=False)
        batch_op.create_unique_constraint('uqx_video_requests_uuid', ['uuid'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('video_requests', schema=None) as batch_op:
        batch_op.drop_constraint('uqx_video_requests_uuid', type_='unique')
        batch_op.drop_index('idx_video_requests_uuid')
        batch_op.drop_column('uuid')

    # ### end Alembic commands ###
